### ISSUE TITLE
2018.3.0b5 HDRP

### ISSUE THREAD

**Issue by Fnatic91** [keijiro/Kino#1]
Shader error, failed to open source file: 'PostProcessing/Shaders/StdLib.hlsl' at line 6 (on d3d11)

Every shader are give this error.

Streak gives:
RenderingCommandBuffer: invalid pass index 1 in DrawMesh 
RenderingCommandBuffer: invalid pass index 2 in DrawMesh  
RenderingCommandBuffer: invalid pass index 3 in DrawMesh

**Comment by keijiro** [comment]
Thanks for reporting the issue. I fixed it in the latest commit.

I'm closing this ticket. Please feel free to reopen if it still reproduces on your side.

**Comment by Hitomilras** [comment]
Reproduced in Unity 2018.3.6f1

**Comment by Hitomilras** [comment]
Getting  the same  error while using PostProcessingStack 2.0 in 2018.3.6f1 on MacOS. 
Disabling post  processing stack fix this issue.

**Comment by Yoshify** [comment]
Chiming in to confirm this is still an issue with PPS 2.1.5 on 2018.3.11f1, HDRP, Windows 10. Only fix is to disable the PPS.

**Comment by keijiro** [comment]
I updated the project with Unity 2019.3 (HDRP 7.1).
