### ISSUE TITLE
Fail to load the package Unity 2019.2.13

### ISSUE THREAD

**Issue by netosama** [keijiro/Kino#10]
I have tried to install Kino from the Package Manager in order to get work with HDRP, but I recieve some errors.
![ERROR](https://user-images.githubusercontent.com/7396615/69673579-9921e500-1068-11ea-967c-24e1d28e61c9.jpg)

**Comment by keijiro** [comment]
Kino requires Unity 2019.3 or later.

2019.2 doesn't support custom post processing effects, so it can't be backported to 2019.2.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further questions.
