### ISSUE TITLE
Kawase blur effect?

### ISSUE THREAD

**Issue by pimpace** [keijiro/Kino#14]
Hey!

It would be awesome if you implemented blur effect (which support transparent objects)!

best regards;
Pimpace

**Comment by keijiro** [comment]
If you meant the depth-of-field effect (it's very different from simple blur effects), it's not possible to implement as a custom post-processing effect. DOF is quite a complex effect. It needs modifying the render pipeline code.

**Comment by keijiro** [comment]
I close this issue as resolved. Please feel free to reopen it for further issues.

**Comment by pimpace** [comment]
hey Keijiro!

No, not depth-of-field. A full screen blur effect as a post-process method. Or what would be better, the ultimate goal would be when you can put a shader on a plane or on a UI element which can blur every object behind.
I found this project https://github.com/sebastianhein/urp_kawase_blur with URP, but the problem is with this, alpha-pixels/transparent object wont show with this method.

That's why I asked you that it could possible to implement such a blur effect into your Kino project. I'm searching a good blur effect for a year from now and I found none. :( I know that it's differ in HDRP and URP, but I couldn't see any solution neither of them.
Maybe you can explain that it's even possible? I mean show transparent object behind blur effect.

![image](https://user-images.githubusercontent.com/18311524/86901651-34099400-c10d-11ea-83e6-18afc9906424.png)

This is the effect I can achieve so far. As you can see, transparent object cannot see behind this shader. There is a ScriptableRenderFeature script in this little project but I cannot figure out how can it work to achieve my goal.
[ShaderTest3_2.zip](https://github.com/keijiro/Kino/files/4889798/ShaderTest3_2.zip)

If you have spare time, can you investigate this sample project please?
Thanks for your help!

Pimpace

ui.: I'm using the latest Unity 2019.4.2f1 LTS version
