### ISSUE TITLE
Access to glitch paramaters

### ISSUE THREAD

**Issue by Drumaddict182** [keijiro/Kino#19]
Hello, i'm trying to access to the glitch parameters via code with the volume component, in order to control them with midi input. But i have an error : "The name 'glitch' does not exist in the current context". I don't understand which name i have to use ? I hope my question is clear. 

Thank you.

**Comment by keijiro** [comment]
I'd recommend using volumes and the Weight property to indirectly control parameters instead of directly accessing those parameters.

**Comment by keijiro** [comment]
I'm closing this issue now. Please reopen it for further problems.
