### ISSUE TITLE
Any chance we can get this for URP as well?

### ISSUE THREAD

**Issue by 4xx31** [keijiro/Kino#20]
Pretty please :) I'm especially interested in the Glitch effect.

Thank you in advance!

**Comment by keijiro** [comment]
Duplicated: #18

**Comment by keijiro** [comment]
I'll implement it when URP adds custom post processing effect support.

**Comment by andybak** [comment]
> I'm especially interested in the Glitch effect.

I haven't tried it but take a look here: https://github.com/YuSiangLai/URP-Custom-Post-Processing

Someone appears to have implemented glitch using URP RenderFeatures

**Comment by 4xx31** [comment]
> > I'm especially interested in the Glitch effect.
> 
> I haven't tried it but take a look here: https://github.com/YuSiangLai/URP-Custom-Post-Processing
> 
> Someone appears to have implemented glitch using URP RenderFeatures

Thank you, but it didn't work for me after importing their package and following the steps. Not even their "TestBed" scene (when running it from inside my project) renders their shaders. I only see:

![image](https://user-images.githubusercontent.com/1570026/193670636-9272fa26-89d5-4693-ae00-29ad4e47115a.png)

**Comment by keijiro** [comment]
@Zedronar You should report the issue to the project owner.
