### ISSUE TITLE
[Android] Streak glitch by Unlit shaders

### ISSUE THREAD

**Issue by stencg** [keijiro/Kino#5]
Any Unlit/... shaders give overbright for Streak. Test in 2018.3.0f2
More info in screenshots
https://prnt.sc/mbj7dq - in editor (work fine)
https://prnt.sc/mbj6vs - in game (have glitch)

p.s.
UI image with full black color too impact Streak fx, if canvas render mode - World Space

**Comment by keijiro** [comment]
Thank you for reporting the issue. Could you provide additional information on it?

- According to the screenshot, this issue was observed on Xiaomi Mi 5s. Is it right?
- Can you reproduce the same issue on other devices?

**Comment by stencg** [comment]
Yes Mi 5s. And yes, reproduced on other devices, but only with GPU Adreno. No problem with Mali (PowerVR I will test later).
I also found that a problem occurs when there are completely black pixels in the texture.

**Comment by keijiro** [comment]
Thanks for the information. It helps me a lot. I'll test it on a device later.

**Comment by keijiro** [comment]
The situation changed in the recent several months -- The post processing stack was deprecated and replaced with built-in post processing effects in the each render pipeline (URP and HDRP). Following this move, I changed the focus of this project to support only HDRP.

I'd like to start another project to support URP when custom effect support is added to it (at the moment URP doesn't support custom post processing effects).

**Comment by andybak** [comment]
> at the moment URP doesn't support custom post processing effects)

I was wondering about this. As a workaround could you use ScriptableRenderPasses as a workaround for the lack of custom post-processing?

**Comment by keijiro** [comment]
I think it's better to wait for post processing support. I don't like to rewrite all the things twice.
