### ISSUE TITLE
Isoline view range

### ISSUE THREAD

**Issue by zeekindustries** [keijiro/Kino#6]
Hey Keijiro!

I wanted to know if there's a way to limit the range of where the isoline starts/finish drawing, I found that the range is given by the camera near/far plane, and tried to modify the ComputeViewSpacePosition in DepthUtils.hlsl but with no success on trying to remap the z buffer.
Was trying to get the isoline grow away from the camera based on some value. Would be great if this feature existed. Thanks a lot! Awesome work as always.

**Comment by keijiro** [comment]
The Isoline effect is removed in the recent update to reduce the cost of maintenance.

**Comment by andybak** [comment]
Would Isoline be particularly tricky to implement on HDRP? I was actually going to have a stab at it myself.

(EDIT - corrected URP to HDRP)

**Comment by keijiro** [comment]
Actually not so tricky. It's just hard to maintain things with HDRP due to its forward-compatibility breaking nature.
